<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="langageCompilation" nsURI="http://www.example.org/langageCompilation"
    nsPrefix="langageCompilation">
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileLoop" eSuperTypes="#//Loop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoopCondition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryOperation" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Substraction" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparaison" abstract="true" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="GT" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assignement" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnInteger" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnString" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LT" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equal" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="Addition" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Division" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplication" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="LTorEqual" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="GTorEqual" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnBoolean" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Different" eSuperTypes="#//Comparaison"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionEtat" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" lowerBound="1" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else" upperBound="-1" eType="#//Statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Condition" lowerBound="1"
        eType="#//BooleanExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodePrint" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        upperBound="-1" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnDouble" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialeValue1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialeValue2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheBoolean" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheDouble" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheInt" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheString" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlusEqual" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="MinusEqual" eSuperTypes="#//BinaryOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engine" upperBound="4"
        eType="#//Engine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" upperBound="4"
        eType="#//Sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Engine" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="LaserSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="WheelEngine" eSuperTypes="#//Engine"/>
  <eClassifiers xsi:type="ecore:EClass" name="EngineOperation" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorOperation" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass43"/>
  <eClassifiers xsi:type="ecore:EClass" name="VitesseOperation" eSuperTypes="#//EngineOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wheelengine" lowerBound="1"
        eType="#//WheelEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colorsensor" lowerBound="1"
        eType="#//ColorSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lasersensor" lowerBound="1"
        eType="#//LaserSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntensityOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colorsensor" lowerBound="1"
        eType="#//ColorSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UltraSonicSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GyroSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="GPSSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="XGPSOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gpssensor" lowerBound="1"
        eType="#//GPSSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGPSOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gpssensor" lowerBound="1"
        eType="#//GPSSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistanceOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ultrasonicsensor" lowerBound="1"
        eType="#//UltraSonicSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AngleOperation" eSuperTypes="#//SensorOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gyrosensor" lowerBound="1"
        eType="#//GyroSensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//BooleanExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="MotorizedArmEngine" eSuperTypes="#//Engine"/>
  <eClassifiers xsi:type="ecore:EClass" name="PositionOperation" eSuperTypes="#//EngineOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="motorizedarmengine" lowerBound="1"
        eType="#//MotorizedArmEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaintballLauncherEngine" eSuperTypes="#//Engine"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForceOperation" eSuperTypes="#//EngineOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="paintballlauncherengine"
        lowerBound="1" eType="#//PaintballLauncherEngine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BreakMotor" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="engine" lowerBound="1"
        eType="#//Engine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Colors">
    <eLiterals name="black"/>
    <eLiterals name="white" value="1"/>
    <eLiterals name="blue" value="2"/>
    <eLiterals name="yellow" value="3"/>
    <eLiterals name="red" value="4"/>
    <eLiterals name="green" value="5"/>
    <eLiterals name="pink" value="6"/>
    <eLiterals name="grey" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnColor" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="#//Colors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TheColor" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Colors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pause" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
