/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LegoLangRuntimeModule extends AbstractLegoLangRuntimeModule {
}
