/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class LegoLangStandaloneSetup extends LegoLangStandaloneSetupGenerated {

	public static void doSetup() {
		new LegoLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
