/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class LegoLangUiModule extends AbstractLegoLangUiModule {

	public LegoLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
