/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import langageCompilation.concrete.syntax.LegoLangRuntimeModule;
import langageCompilation.concrete.syntax.LegoLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class LegoLangIdeSetup extends LegoLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new LegoLangRuntimeModule(), new LegoLangIdeModule()));
	}
	
}
