/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.ide;


/**
 * Use this class to register ide components.
 */
public class LegoLangIdeModule extends AbstractLegoLangIdeModule {
}
