/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.ui.tests;

import com.google.inject.Injector;
import langageCompilation.concrete.syntax.ui.internal.SyntaxActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LegoLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SyntaxActivator.getInstance().getInjector("langageCompilation.concrete.syntax.LegoLang");
	}

}
