/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLegoLangScopeProvider extends DelegatingScopeProvider {
}
