/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.parser.antlr;

import com.google.inject.Inject;
import langageCompilation.concrete.syntax.parser.antlr.internal.InternalLegoLangParser;
import langageCompilation.concrete.syntax.services.LegoLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LegoLangParser extends AbstractAntlrParser {

	@Inject
	private LegoLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLegoLangParser createParser(XtextTokenStream stream) {
		return new InternalLegoLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public LegoLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LegoLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
