/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LegoLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("langageCompilation/concrete/syntax/parser/antlr/internal/InternalLegoLang.tokens");
	}
}
