/*
 * generated by Xtext 2.25.0
 */
package langageCompilation.concrete.syntax.ui;

import com.google.inject.Injector;
import langageCompilation.concrete.syntax.ui.internal.SyntaxActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LegoLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SyntaxActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SyntaxActivator activator = SyntaxActivator.getInstance();
		return activator != null ? activator.getInjector(SyntaxActivator.LANGAGECOMPILATION_CONCRETE_SYNTAX_LEGOLANG) : null;
	}

}
